# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H <- function(Phi, Dist, KernInd, T) {
    .Call('_dependentGP_H', PACKAGE = 'dependentGP', Phi, Dist, KernInd, T)
}

lmcGP_Rcpp <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, McmcObj_List, RawSamples, Interactive, Verbose) {
    .Call('_dependentGP_lmcGP_Rcpp', PACKAGE = 'dependentGP', DatObj_List, HyPara_List, MetrObj_List, Para_List, McmcObj_List, RawSamples, Interactive, Verbose)
}

PredY <- function(NKeep, NVisitsReturn, K, Gamma, T, Phi, TimeDist, KernInd, OriginalVisits, NewVisits, NNewVisitsReturn, NOriginalReturn, WhichOriginalReturnLong, WhichOriginalReturn, WhichNewReturn, A, AInd, Sigma2, NVisits, Verbose) {
    .Call('_dependentGP_PredY', PACKAGE = 'dependentGP', NKeep, NVisitsReturn, K, Gamma, T, Phi, TimeDist, KernInd, OriginalVisits, NewVisits, NNewVisitsReturn, NOriginalReturn, WhichOriginalReturnLong, WhichOriginalReturn, WhichNewReturn, A, AInd, Sigma2, NVisits, Verbose)
}

PredDerv <- function(NKeep, NNewVisits, K, Phi, Sigma2, A, AInd, N, IndecesOrg, Time, IndecesNew, Y, TimesSort, Verbose) {
    .Call('_dependentGP_PredDerv', PACKAGE = 'dependentGP', NKeep, NNewVisits, K, Phi, Sigma2, A, AInd, N, IndecesOrg, Time, IndecesNew, Y, TimesSort, Verbose)
}

Play <- function() {
    invisible(.Call('_dependentGP_Play', PACKAGE = 'dependentGP'))
}

CholInv <- function(Cov) {
    .Call('_dependentGP_CholInv', PACKAGE = 'dependentGP', Cov)
}

makeSymm <- function(A) {
    .Call('_dependentGP_makeSymm', PACKAGE = 'dependentGP', A)
}

